aliyun/openapi-sdk-php-client

.travis.yml, src/Config/Data.php, src/Credentials/Ini/CreateTrait.php, src/Credentials/Ini/IniCredential.php, src/Credentials/Providers/EcsRamRoleProvider.php, src/Credentials/Providers/RamRoleArnProvider.php, src/Http/GuzzleTrait.php, src/Request/RoaRequest.php, src/Request/Traits/AcsTrait.php, src/Request/Traits/ClientTrait.php, src/Result/ArrayAccessTrait.php, src/Result/FormatTrait.php, src/Result/HasDataTrait.php, src/Result/Result.php, tests/Unit/Credentials/Ini/CreateTraitTest.php, tests/Unit/Credentials/Ini/IniCredentialTest.php, tests/Unit/DefaultAcsClientTest.php, tests/Unit/Request/RequestTest.php, tests/Unit/Request/RoaRequestTest.php, tests/Unit/Result/FormatTraitTest.php, tests/Unit/Result/HasDataTraitTest.php, tests/Unit/Result/ResultTest.php
- Improve unit testing
- Optimize logic
- Modify the CI configuration file
=> Improve unit testing & Optimize logic

phpunit.xml, src/Config/Data.php, src/Constants/Business.php, src/Request/Request.php, src/Request/RoaRequest.php, src/Request/Traits/DeprecatedRoaTrait.php, src/Request/Traits/DeprecatedTrait.php, tests/Feature/Request/RequestTest.php, tests/Unit/Request/DeprecatedRoaTraitTest.php, tests/Unit/Request/DeprecatedTraitTest.php, tests/Unit/Request/RequestTest.php
- Add endpoint
- Perfect configuration
=> Improve unit testing for Request.

README-CN.md, README.md
1. Support more badges.
2. Use a more appropriate demo parameter.
=> modify readme

src/Request/RoaRequest.php, tests/Unit/Request/DeprecatedRoaTraitTest.php
=> Init pathPattern in ROA

src/Result/Result.php
Make response message body to string anytime.
=> Result to String

README.md, src/Request/Traits/AcsTrait.php, tests/Unit/Request/AcsTraitTest.php
Catch exception for resolve host.
=> Catch exception for resolve host.

README-CN.md, README.md
1. Link sdk php
2. Correction descriptions.
=> Link sdk php

README-CN.md, README.md, composer.json, composer.lock
=> remove branch alias

README-CN.md, README.md, src/Config/Config.php, src/Config/Data.php, src/Constants/Business.php, src/Exception/ServerException.php, src/Regions/LocationService.php, src/Request/Traits/AcsTrait.php, src/Traits/EndpointTrait.php, tests/Unit/Traits/EndpointTraitTest.php
1. Add endpoints.
2. Adjust parameter locations to accommodate global endpoints in the future.
3. Handling location service exceptions.
4. Improve exception message.
=> Location & Endpoints

README-CN.md, README.md, src/Regions/LocationService.php, tests/Feature/Credentials/AccessKeyCredentialTest.php, tests/Feature/Credentials/BearerTokenCredentialTest.php, tests/Feature/Credentials/EcsRamRoleCredentialTest.php, tests/Feature/Credentials/RamRoleArnCredentialTest.php, tests/Unit/DefaultAcsClientTest.php, tests/Unit/Request/AcsTraitTest.php, tests/Unit/Traits/EndpointTraitTest.php
1. Adjust location logic
2. Changed README
=> Adjust location logic & Changed README 

CHANGELOG.md, README-CN.md, README.md, UPGRADING.md, composer.json, composer.lock, src/Config/Data.php, src/DefaultAcsClient.php, src/Regions/LocationService.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Request/Traits/AcsTrait.php, src/Traits/HasDataTrait.php, tests/Mock/Services/Rds/DeleteDatabaseRequestMock.php, tests/Unit/Clients/ClientTest.php, tests/Unit/Regions/LocationServiceTest.php, tests/Unit/Request/AcsTraitTest.php, tests/Unit/Traits/EndpointTraitTest.php
1. Change readme.
2. Optimization logic.
=> change readme and optimization logic

README-CN.md, README.md
1. Increase the DingTalk QR code.
2. Align the demo code.
=> support dingtalk

README-CN.md, README.md
=> add region to readme

.travis.yml, README-CN.md, README.md, appveyor.yml, src/Exception/ServerException.php, tests/Feature/Request/DistinguishSignatureAndCredentialErrorsTest.php, tests/Unit/DefaultAcsClientTest.php, tests/Unit/Request/RequestTest.php
=> change README.md

src/Config/Data.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, tests/Feature/Request/RequestTest.php, tests/Feature/Request/RpcRequestTest.php, tests/Unit/Request/RpcRequestTest.php
- Support Region environment variable.
- Add Endpoints.
=> Support Region environment variable

.scrutinizer.yml, .travis.yml, CHANGELOG.md, appveyor.yml, codecov.yml, src/AlibabaCloud.php, src/Config/Data.php
- Add endpoints for ApiGateway in Silicon Valley, Virginia.
- Add endpoints for Image Search in Shanghai.
=> Add endpoints for ApiGateway and Image Search

README-CN.md, README.md, tests/bootstrap.php
- Update readme.
- Update bootstrap for test.
=> update readme and bootstrap for test

CHANGELOG.md, src/Config/Data.php
=> add endpoints

.gitignore, composer.json, src/AlibabaCloud.php, tests/bootstrap.php
=> optimized env and composer.json

src/Request/Request.php, src/Request/UserAgent.php, src/Traits/RequestTrait.php, tests/Unit/Request/AcsTraitTest.php, tests/Unit/Request/UserAgentTest.php
=> only append ua

CHANGELOG.md, src/AlibabaCloud.php
=> `userAgent` is renamed to `userAgentAppend`

CHANGELOG.md, src/Request/Request.php, src/Traits/RequestTrait.php, tests/Unit/Request/AcsTraitTest.php, tests/Unit/Request/UserAgentTest.php
`userAgentAppend` is renamed to `appendUserAgent`.
=> `userAgentAppend` is renamed to `appendUserAgent`.

src/Clients/EcsRamRoleClient.php, src/Clients/ManageTrait.php, src/Clients/StsClient.php, src/Request/Request.php, src/Request/UserAgent.php, src/Traits/RequestTrait.php, tests/Feature/Request/RpcRequestTest.php, tests/Unit/Request/AcsTraitTest.php, tests/Unit/Request/UserAgentTest.php
=> improve user agent class

src/Credentials/Providers/EcsRamRoleProvider.php, src/Credentials/Providers/Provider.php, src/Credentials/Providers/RamRoleArnProvider.php, tests/Unit/Request/UserAgentTest.php
=> improve tests

src/Credentials/Ini/IniCredential.php
=> fixed permisson for credential

src/Credentials/Ini/IniCredential.php, tests/Unit/Credentials/Ini/IniCredentialTest.php, tests/Unit/Traits/ClientTraitTest.php
=> support open_basedir in vh

CHANGELOG.md, src/AlibabaCloud.php
=> update version adn changelog

CHANGELOG.md, composer.json, src/AlibabaCloud.php, src/Release.php, tests/Feature/Request/RpcRequestTest.php
- Support Release Script `composer release`.
- Add endpoints for apigateway in `drdspre` in `cn-qingdao`.
- Add endpoints for apigateway in `drdspre` in `cn-beijing`.
- Add endpoints for apigateway in `drdspre` in `cn-hangzhou`.
- Add endpoints for apigateway in `drdspre` in `cn-shanghai`.
- Add endpoints for apigateway in `drdspre` in `cn-shenzhen`.
- Add endpoints for apigateway in `drdspre` in `cn-hongkong`.
- Add endpoints for apigateway in `drdspost` in `ap-southeast-1`.
- Add endpoints for apigateway in `drdspost` in `cn-shanghai`.
- Add endpoints for apigateway in `drdspost` in `cn-hongkong`.
- Add endpoints for apigateway in `vod` in `ap-southeast-1`.
- Add endpoints for apigateway in `vod` in `eu-central-1`.
=> support release tool

README-CN.md, README.md, composer.json, src/Helpers.php, src/Request/Request.php, tests/Feature/Request/RequestDebugTest.php, tests/Unit/AlibabaCloudTest.php, tests/Unit/Clients/BearerTokenClientTest.php, tests/Unit/Clients/RamRoleArnClientTest.php, tests/Unit/DefaultAcsClientTest.php, tests/Unit/HelpersTest.php
- Support enable debug mode by set `DEBUG=sdk` environment variables.
- Update README.md
- Add Unit Test.
=> support debug by set environment variables

CHANGELOG.md, src/AlibabaCloud.php
=> release V1.0.14

src/Config/Data.php
- Add endpoints for `Chatbot`.
- Change endpoints for `drdspost` and `drdspre`.
=> change_endpoint

src/Request/Request.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, tests/Feature/Request/RpcRequestTest.php, tests/Unit/Request/RpcRequestTest.php
- improve tests.
- remove redundant parameters.
=> Improve Request

CHANGELOG.md, src/AlibabaCloud.php
=> Release 1.0.15

codecov.yml, src/Functions.php, tests/Unit/Credentials/Ini/IniCredentialTest.php
=> improve functions

README-CN.md, README.md, docs/Client-CN.md, docs/Client-EN.md
=> Improve Doc

src/Clients/ManageTrait.php, src/Credentials/Providers/CredentialsProvider.php, src/Credentials/Providers/EcsRamRoleProvider.php, src/Credentials/Providers/Provider.php, src/Credentials/Providers/RamRoleArnProvider.php, src/Credentials/Providers/RsaKeyPairProvider.php, src/Request/Traits/ClientTrait.php, tests/Feature/Credentials/AccessKeyCredentialTest.php, tests/Feature/Credentials/BearerTokenCredentialTest.php, tests/Feature/Credentials/EcsRamRoleCredentialTest.php, tests/Feature/Credentials/RamRoleArnCredentialTest.php, tests/Feature/Credentials/RsaKeyPairCredentialTest.php, tests/Feature/Request/ChainProviderRequestTest.php, tests/Feature/Request/DistinguishSignatureAndCredentialErrorsTest.php, tests/Feature/Request/RequestDebugTest.php, tests/Feature/Request/RequestTest.php, tests/Feature/Request/RoaRequestTest.php, tests/Feature/Request/RpcRequestTest.php, tests/Framework/RequestCompatibilityTest.php, tests/Unit/Regions/LocationServiceTest.php
=> improve design

CHANGELOG.md, docs/Client-EN.md, src/AlibabaCloud.php, src/Clients/Client.php, src/Credentials/Providers/CredentialsProvider.php, src/Credentials/Providers/RamRoleArnProvider.php, src/Credentials/Providers/RsaKeyPairProvider.php, src/Credentials/Requests/GenerateSessionAccessKey.php, src/Exception/ServerException.php, src/Regions/LocationService.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/SDK.php, tests/Feature/Credentials/BearerTokenCredentialTest.php, tests/Unit/Exception/ServerExceptionTest.php, tests/Unit/Regions/LocationServiceTest.php, tests/Unit/Traits/EndpointTraitTest.php
=> improve doc (#78)

src/AlibabaCloud.php, src/Credentials/Providers/EcsRamRoleProvider.php, src/Exception/ServerException.php, src/Regions/LocationService.php, src/Request/Request.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Request/Traits/AcsTrait.php, src/Traits/MockTrait.php, tests/Feature/Credentials/RsaKeyPairCredentialTest.php, tests/Feature/Request/RoaRequestTest.php, tests/Feature/Request/RpcRequestTest.php, tests/Unit/Credentials/Providers/EcsRamRoleProviderTest.php, tests/Unit/Credentials/Providers/RamRoleArnProviderTest.php, tests/Unit/Credentials/Providers/RsaKeyPairProviderTest.php, tests/Unit/DefaultAcsClientTest.php, tests/Unit/Regions/LocationServiceTest.php, tests/Unit/Request/AcsTraitTest.php
=> support mock

README-CN.md, README.md, tests/Feature/Regions/EndpointTraitTest.php, tests/Unit/Clients/ManageTraitTest.php, tests/Unit/Request/Traits/ClientTraitTest.php
=> update doc and improve tests

CHANGELOG.md, appveyor.yml, src/AlibabaCloud.php, src/Config/Data.php, src/Request/Request.php
=> SSL certificates are not validated by default

CHANGELOG.md, src/AlibabaCloud.php
=> Add SSL Verify Option

composer.json
=> remove qa tools

.gitattributes, tests/Framework/RequestCompatibilityTest.php
=> git attributes

.scrutinizer.yml, .travis.yml, appveyor.yml, tests/Feature/Request/ProxyTest.php
=> proxy tests

CHANGELOG.md, src/AlibabaCloud.php
=> Remove SVG

CHANGELOG.md, composer.json, docs/9-Log-CN.md, docs/9-Log-EN.md, src/AlibabaCloud.php, src/Request/Request.php, src/Traits/LogTrait.php, tests/Unit/Traits/LogTraitTest.php
=> support log

docs/9-Log-CN.md, docs/9-Log-EN.md, src/Traits/LogTrait.php
=> update logger format

CHANGELOG.md, src/AlibabaCloud.php, src/Config/Data.php
=> Updated default log format

CHANGELOG.md, docs/9-Log-CN.md, docs/9-Log-EN.md, src/AlibabaCloud.php, src/Log/LogFormatter.php, src/Request/Request.php, src/Traits/LogTrait.php, tests/Mock/VirtualFile.php, tests/Unit/Traits/LogTraitTest.php
=> improve logger

src/Clients/RamRoleArnClient.php, src/Credentials/RamRoleArnCredential.php, src/Credentials/Requests/AssumeRole.php, src/Traits/ClientTrait.php, tests/Feature/Credentials/RamRoleArnCredentialTest.php, tests/Unit/Credentials/RamRoleArnCredentialTest.php
=> support policy

CHANGELOG.md, src/AlibabaCloud.php
=> Support `Policy` for `ramRoleArnClient`

src/Clients/RamRoleArnClient.php, src/Credentials/RamRoleArnCredential.php, src/Credentials/Requests/AssumeRole.php, src/Traits/ClientTrait.php
=> improve policy

CHANGELOG.md, composer.json, src/AlibabaCloud.php
=> updated composer.json

CHANGELOG.md, README-CN.md, README.md, docs/0-Prerequisites-CN.md, docs/0-Prerequisites-EN.md, docs/1-Installation-CN.md, docs/1-Installation-EN.md, src/AlibabaCloud.php, src/Config/Data.php, src/Exception/ClientException.php, src/Request/Traits/AcsTrait.php, tests/Unit/Config/ConfigTest.php, tests/Unit/Request/AcsTraitTest.php
=> updated readme

tests/Feature/Credentials/RamRoleArnCredentialTest.php
=> Added test policy as array

CHANGELOG.md, composer.json, src/AlibabaCloud.php, src/Request/Traits/AcsTrait.php, tests/Unit/Request/AcsTraitTest.php
=> Improve exception message for `Region ID`

CHANGELOG.md, src/Request/Traits/AcsTrait.php, src/SDK.php, tests/Unit/Request/AcsTraitTest.php
=> Improve exception code and message for `Region ID`

src/Request/Request.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Request/Traits/AcsTrait.php, tests/Unit/Request/AcsTraitTest.php, tests/Unit/Request/RpcRequestTest.php
=> improve methods

CHANGELOG.md, composer.json, src/AlibabaCloud.php, src/Config/Data.php, src/Credentials/Providers/CredentialsProvider.php, src/Credentials/Providers/EcsRamRoleProvider.php, src/Exception/ServerException.php, src/Request/Request.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Traits/HasDataTrait.php, tests/Unit/Request/RoaRequestTest.php, tests/Unit/Request/RpcRequestTest.php
=> Optimize request processing logic.

CHANGELOG.md, src/AlibabaCloud.php, src/Request/Request.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, tests/Unit/Request/RoaRequestTest.php, tests/Unit/Request/RpcRequestTest.php, tests/Unit/Request/Traits/ClientTraitTest.php
=> improve request parameters

src/Credentials/Providers/CredentialsProvider.php, src/Exception/ServerException.php, src/Log/LogFormatter.php, src/Request/Request.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Request/Traits/ClientTrait.php, src/Request/UserAgent.php, src/Traits/MockTrait.php, tests/Unit/Request/RequestTest.php, tests/Unit/Request/Traits/ClientTraitTest.php
=> improve 2.0.0

src/Accept.php, src/Filter/HttpFilter.php, src/Request/Request.php, src/Request/RoaRequest.php, tests/Feature/Request/RoaRequestTest.php, tests/Unit/Request/RoaRequestTest.php
=> improve body encode

src/Request/RoaRequest.php, tests/Unit/Filter/HttpFilterTest.php, tests/Unit/Request/RoaRequestTest.php, tests/Unit/Request/RpcRequestTest.php, tests/Unit/Request/Traits/ClientTraitTest.php
=> Improved design and added tests for Filter

CHANGELOG.md, UPGRADING.md, src/AlibabaCloud.php
=> release v1.3.0

CHANGELOG.md, composer.json, src/AlibabaCloud.php
=> Allow timeouts to be set in microseconds

.travis.yml, docs/3-Request-CN.md, docs/3-Request-EN.md, src/Filter/ClientFilter.php, src/Request/Request.php, src/Request/Traits/RetryTrait.php, tests/Feature/Request/RequestAsyncTest.php, tests/Feature/Request/RetryByClientTest.php, tests/Feature/Request/RetryByServerTest.php
=> Retry & Async

CHANGELOG.md, src/AlibabaCloud.php
=> Release 1.4.0

tests/Feature/Request/RetryByClientTest.php, tests/Feature/Request/RetryByServerTest.php, tests/Unit/Filter/ClientFilterTest.php
Improve Feature tests for Retry.
=> Improve tests for retry

src/AlibabaCloud.php
=> improved resolver for products

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.0

src/AlibabaCloud.php
=> improve resolver

src/AlibabaCloud.php, src/Resolver/ActionResolverTrait.php, src/Resolver/ApiResolver.php, src/Resolver/CallTrait.php, src/Resolver/Roa.php, src/Resolver/Rpc.php, src/Resolver/VersionResolver.php
=> supported ide-helper

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.1

docs/3-Request-CN.md, docs/3-Request-EN.md, docs/4-Result-CN.md, docs/4-Result-EN.md, src/AlibabaCloud.php, src/Credentials/Providers/EcsRamRoleProvider.php, src/Exception/ServerException.php, src/Request/Request.php, src/Request/Traits/RetryTrait.php, src/Result/Result.php, tests/Feature/Request/ProxyTest.php, tests/Feature/Request/RequestAsyncTest.php, tests/Unit/AlibabaCloudTest.php, tests/Unit/Result/ResultTest.php, tests/Unit/Traits/MockTraitTest.php
=> improved result object

CHANGELOG.md, src/AlibabaCloud.php, src/Resolver/ActionResolverTrait.php, src/Resolver/Roa.php, src/Resolver/Rpc.php
=> Improved `Result` object

CHANGELOG.md, src/AlibabaCloud.php, src/Config/Data.php
=> release 1.5.3

src/Resolver/ActionResolverTrait.php, src/Resolver/ApiResolver.php, src/Resolver/CallTrait.php, src/Resolver/Roa.php, src/Resolver/Rpc.php, src/Resolver/VersionResolver.php, src/Result/Result.php
=> improved comment

docs/5-Region-CN.md, docs/5-Region-EN.md, docs/6-Host-CN.md, docs/6-Host-EN.md, docs/7-Verify-CN.md, docs/7-Verify-EN.md
=> Updated docs

src/Config/Data.php, src/Request/RoaRequest.php
=> fixed header and updated endpoints

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.4

composer.json, src/Config/Data.php, src/Functions.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Request/Traits/ClientTrait.php, src/Request/UserAgent.php, src/Signature/BearerTokenSignature.php, src/Signature/ShaHmac1Signature.php, src/Signature/ShaHmac256Signature.php, src/Signature/ShaHmac256WithRsaSignature.php, src/Signature/Signature.php, src/Support/Arrays.php, src/Support/Path.php, src/Support/Sign.php, src/Traits/HttpTrait.php, tests/Unit/Request/RoaRequestTest.php, tests/Unit/Request/RpcRequestTest.php, tests/Unit/Support/ArraysTest.php
=> improved sign

CHANGELOG.md
=> release 1.5.5

README-CN.md, README.md, docs/8-Debug-CN.md, docs/8-Debug-EN.md, docs/en/0-Prerequisites.md, docs/en/1-Installation.md, docs/en/10-Test.md, docs/en/2-Client.md, docs/en/3-Request.md, docs/en/4-Result.md, docs/en/5-Region.md, docs/en/6-Host.md, docs/en/7-Verify.md, docs/en/8-Debug.md, docs/en/9-Log.md, docs/zh/0-Prerequisites.md, docs/zh/1-Installation.md, docs/zh/10-Test.md, docs/zh/2-Client.md, docs/zh/3-Request.md, docs/zh/4-Result.md, docs/zh/5-Region.md, docs/zh/6-Host.md, docs/zh/7-Verify.md, docs/zh/8-Debug.md, docs/zh/9-Log.md, src/AlibabaCloud.php
=> improved docs

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.6

CHANGELOG.md, composer.json, src/AlibabaCloud.php, src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Support/Sign.php, tests/Unit/Support/SignTest.php
=> release 1.5.7

CHANGELOG.md, composer.json, src/AlibabaCloud.php, src/Result/Result.php, src/Support/Arrays.php, tests/Unit/Support/ArraysTest.php
=> Improved `Arrays`

src/Request/RoaRequest.php, src/Request/RpcRequest.php, src/Support/Sign.php, tests/Unit/Support/SignTest.php
=> Improved `uuid`

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.9

src/Request/Traits/AcsTrait.php
=> improve endpoints

composer.json, src/Config/Data.php, src/Resolver/CallTrait.php
=> removed class_map

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.10

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.11

src/Request/RoaRequest.php, src/Support/Sign.php
=> improved sign for roa

CHANGELOG.md, src/AlibabaCloud.php
=> Fixed Signature for ROA

src/AlibabaCloud.php, src/Config/Data.php, src/Filter/ApiFilter.php, src/Request/Traits/AcsTrait.php, src/Resolver/ApiResolver.php
=> improved endpoint map

src/Filter/CredentialFilter.php, src/Traits/ClientTrait.php, tests/Unit/Filter/CredentialFilterTest.php
=> improved filter

CHANGELOG.md, src/AlibabaCloud.php
=> Improved Credential Filter

src/Config/Data.php, src/Request/Traits/AcsTrait.php
=> Improved Request Design

src/Request/Traits/AcsTrait.php
Optimize request design to reduce complexity.
=> Improved Request

CHANGELOG.md, src/AlibabaCloud.php, src/Clients/Client.php, tests/Feature/Request/RequestAsyncTest.php
=> Improved Client

CHANGELOG.md, src/AlibabaCloud.php
=> Already up to data

tests/Unit/Credentials/RsaKeyPairCredentialTest.php
=> Fixed file name

README.md
=> updated doc

README.md, src/Request/Traits/AcsTrait.php, src/Traits/EndpointTrait.php
=> Fixed find host

README-zh-CN.md, README.md
=> Fixed Badge

CHANGELOG.md, src/AlibabaCloud.php, src/Config/Data.php
- Updated Request link.
- Updated Endpoints data.
=> Updated Request Link

CHANGELOG.md, src/AlibabaCloud.php, src/Config/Data.php
=> updated endpoints

CHANGELOG.md, docs/en-US/3-Request.md, docs/zh-CN/3-Request.md, src/AlibabaCloud.php, src/Config/Data.php
=> Updated endpoints & improved docs

LICENSE.md, NOTICE.md, README-zh-CN.md, README.md
=> updated copyright

CHANGELOG.md, src/AlibabaCloud.php, src/Config/Data.php, src/Support/Sign.php, tests/Unit/Credentials/Providers/EcsRamRoleProviderTest.php, tests/Unit/Credentials/Providers/ProviderTest.php, tests/Unit/Credentials/Providers/RamRoleArnProviderTest.php, tests/Unit/Credentials/Providers/RsaKeyPairProviderTest.php, tests/Unit/Support/SignTest.php
=> Improved Noce

README-zh-CN.md, README.md
=> Updated readme files

composer.json, tests/Feature/Request/RoaRequestTest.php
=> Updated Guzzle

.travis.yml, tests/Unit/Request/ArrayAccessTraitTest.php
=> improved_tests

CHANGELOG.md, src/AlibabaCloud.php, src/Config/Data.php, src/Request/Traits/AcsTrait.php, src/Traits/EndpointTrait.php, tests/Feature/Product/RamTest.php, tests/Unit/Traits/EndpointTraitTest.php
=> Optimize global product support

codecov.yml
=> Improved CodeCov Target

CHANGELOG.md, src/AlibabaCloud.php
=> release 1.5.24

CHANGELOG.md, src/AlibabaCloud.php, src/Encode.php, src/Log/LogFormatter.php, src/Request/Request.php, src/Traits/LogTrait.php, tests/Feature/Request/RequestAsyncTest.php, tests/Unit/Clients/RamRoleArnClientTest.php, tests/Unit/Request/RoaRequestTest.php
=> Fixed ROA signature

.travis.yml, composer.json, src/Filter/ApiFilter.php, src/Filter/ClientFilter.php, tests/Unit/Filter/ApiFilterTest.php, tests/Unit/Filter/ClientFilterTest.php
=> validate region id

composer.json
=> fix composer error config

CHANGELOG.md, src/AlibabaCloud.php
=> Release 1.5.28

src/Support/Sign.php
=> Fixed RPC Sign

CHANGELOG.md, src/AlibabaCloud.php
=> Release 1.5.29

README-zh-CN.md, README.md
=> Added troubleshoot link

.github/ISSUE_TEMPLATE/1-troubleshoot.md, .github/ISSUE_TEMPLATE/5-troubleshoot-cn.md
=> Improved text for troubleshoot

.github/ISSUE_TEMPLATE/1-troubleshoot.md, .github/ISSUE_TEMPLATE/5-troubleshoot-cn.md
=> Improved ts text

.github/ISSUE_TEMPLATE/1-troubleshoot.md, .github/ISSUE_TEMPLATE/5-troubleshoot-cn.md
=> Improved about tpl

CHANGELOG.md
=> Bump 1.5.30

README-zh-CN.md
=> Update OpenAPI portal link

CHANGELOG.md, src/Request/Request.php
=> Fix: parse query
